---
- hosts: 127.0.0.1
  gather_facts: true
  vars:
    full_system_update: ${full_system_update}
  tasks:
    - name: Update | Run system security update for CentOS
      yum:
        name: "*"
        security: yes
        state: latest
      when: ansible_distribution == 'CentOS'
    
    - name: Update | Run system security update for Ubuntu
      apt:
        name: "*"
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: Update | Restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: ( full_system_update|bool )

    - name: Update | Wait for 10 seconds
      pause:
      seconds: 10
      when: ( full_system_update|bool )

    - name: Update | Wait for the system to reboot
      wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60
      when: ( full_system_update|bool )