---
- hosts: 127.0.0.1
  gather_facts: true
  vars:
    # EPEL Repo details | Only for CentOS
    epel_repo_url: ${epel_repo_url}
    epel_repo_gpg_key_url: ${epel_repo_gpg_key_url}
    epel_repofile_path: ${epel_repofile_path}
    ssl_admin_email: ${ssl_admin_email}
    # General settings | VPN Domain
    openvpn_server_domain: ${openvpn_dns_name}
    hostname: ${ec2_hostname}
    s3_bucket: ${s3_bucket}
  tasks:
    - name: Cerbot | Check if EPEL repo is already configured for CentOS
      stat: path={{ epel_repofile_path }}
      when: ansible_distribution == 'CentOS'

    - name: Cerbot | Install EPEL repo for CentOS
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Cerbot | Import EPEL GPG key for CentOS
      rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Cerbot | Install Cerbot for CentOS
      yum:
        name: certbot
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Cerbot | App Cerbot repository for Ubuntu
      apt_repository:
        repo: ppa:certbot/certbot
      when: ansible_distribution == 'Ubuntu'

    - name: Cerbot | Install Cerbot for Ubuntu
      apt:
        name: python-certbot-apache
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Certbot | Stop VPN service
      systemd:
        name: openvpnas
        state: stopped

    - name: Certbot | Check if the certs exists in S3
      shell: aws s3 ls s3://{{ s3_bucket }}/certs/{{ openvpn_server_domain }}/ | wc -l
      register: fileCount

    - set_fact:
        s3fileCount: "{{ fileCount.stdout_lines|max }}"

    - name: Create certificate path
      file:
        path: /etc/letsencrypt/live/{{ openvpn_server_domain }}/
        state: directory
        mode: '0755'
        recurse: yes
      when: s3fileCount|int > 2

    - name: Certbot | Download S3 certificate files
      command: aws s3 cp s3://{{ s3_bucket }}/certs/{{ openvpn_server_domain }}/cert.pem /etc/letsencrypt/live/{{ openvpn_server_domain }}/cert.pem
      when: s3fileCount|int > 2

    - name: Certbot | Download S3 certificate files
      command: aws s3 cp s3://{{ s3_bucket }}/certs/{{ openvpn_server_domain }}/chain.pem /etc/letsencrypt/live/{{ openvpn_server_domain }}/chain.pem
      when: s3fileCount|int > 2

    - name: Certbot | Download S3 certificate files
      command: aws s3 cp s3://{{ s3_bucket }}/certs/{{ openvpn_server_domain }}/fullchain.pem /etc/letsencrypt/live/{{ openvpn_server_domain }}/fullchain.pem
      when: s3fileCount|int > 2

    - name: Certbot | Download S3 certificate files
      command: aws s3 cp s3://{{ s3_bucket }}/certs/{{ openvpn_server_domain }}/privkey.pem /etc/letsencrypt/live/{{ openvpn_server_domain }}/privkey.pem
      when: s3fileCount|int > 2
      
    - name: Cerbot | Request certificate
      command: certbot certonly --standalone -d {{ openvpn_server_domain }} --email {{ ssl_admin_email }} --agree-tos --non-interactive
      register: certificate_request
      when: s3fileCount|int == 0

    - name: Certbot | Start VPN service
      systemd:
        name: openvpnas
        state: restarted
      when: certificate_request.changed

    - name: Cerbot | Check the auto-generated cert path
      stat:
        path: /etc/letsencrypt/live/{{ openvpn_server_domain }}-*
      register: auto_gen_cert_path

    - name: Cerbot | Rename certificate directory
      shell: mv {{ openvpn_server_domain }}-* {{ openvpn_server_domain }}
      args:
       chdir: /etc/letsencrypt/live
       creates: /etc/letsencrypt/live/{{ openvpn_server_domain }}
      when: auto_gen_cert_path.stat.exists and auto_gen_cert_path.stat.isdir

    - name: Cerbot | Upload ca_bundle
      command: /usr/local/openvpn_as/scripts/confdba -mk cs.ca_bundle -v "/etc/letsencrypt/live/{{ openvpn_server_domain }}/fullchain.pem"
      when: certificate_request.changed

    - name: Cerbot | Upload priv_key
      command: /usr/local/openvpn_as/scripts/confdba -mk cs.priv_key -v "/etc/letsencrypt/live/{{ openvpn_server_domain }}/privkey.pem"
      when: certificate_request.changed

    - name: Certbot | Upload certificate
      command: /usr/local/openvpn_as/scripts/confdba -mk cs.cert -v "/etc/letsencrypt/live/{{ openvpn_server_domain }}/cert.pem"
      when: certificate_request.changed

    - name: Certbot | Upload certs to S3
      shell: "cd /etc/letsencrypt/live/{{ openvpn_server_domain }} && aws s3 cp {{ item }} s3://{{ s3_bucket }}/certs/{{ openvpn_server_domain }}/{{ item }}"
      with_items:
        - cert.pem
        - chain.pem
        - fullchain.pem
        - privkey.pem
      when: certificate_request.changed

    - name: Certbot | Restart VPN service
      systemd:
        name: openvpnas
        state: restarted